routes/web.php
    Route::get('venta/verifica/caja', 'VentaController@verificaCajaAjax')->name('venta.verifica.caja');
    Route::get('venta/get/modificaciones', 'VentaController@getModificaciones')->name('venta.get.modificaciones');
    Route::get('venta/store/modify/det', 'VentaController@storeModifyDet')->name('venta.store.modify');
    Route::get('venta/temp/detalles/{venta}', 'VentaController@getDetalles')->name('venta.temp.detalles');

    /**
     * Rutas para graficas
     */
    Route::get('graficas/ventas/dia', 'DashBoardController@graficaVentasDia')->name('graficas.ventas.dia');
    Route::get('graficas/ventas/mes', 'DashBoardController@graficaVentasMes')->name('graficas.ventas.mes');
    Route::get('graficas/ventas/anio', 'DashBoardController@graficaVentasAnio')->name('graficas.ventas.anio');

    /**
     * Rutas para reportes
     */
    Route::get('rpt/ventas/cat', 'RptVentasController@index')->name('rpt.ventas.cats');
    Route::get('rpt/ventas/cat/res', 'RptVentasController@porCatRes')->name('rpt.ventas.cats.res')->middleware(\App\Http\Middleware\SuperAdmin::class);
    Route::get('rpt/resumen', 'RptResumenController@index')->name('rpt.resumen');
    Route::get('rpt/kardex', 'RptGenController@kardex')->name('rpt.kardex');
    Route::get('rpt/gastos', 'GastoController@rpt')->name('rpt.gastos');
    Route::get('rpt/stock','StockController@rpt')->name('rpt.stock');
    Route::get('rpt/compras/','CompraController@rptComprasDiarias')->name('rpt.compras');

    /**
     * Rutas para contabilidad
     */
    Route::resource('gastos', 'GastoController');
    Route::resource('cretiros', 'CretiroController');
    Route::get('cajas/retiro', 'CretiroController@create')->name('caja.retiro');
    Route::resource('cuadres', 'CuadreController');

    /**
     * Rutas para pedidos
     */
    Route::resource('pedidos/pestados', 'PestadoController');
    Route::resource('pedidos/pedidos', 'PedidoController');
    Route::post('pedidos/procesar/{tempPedido}', 'PedidoController@procesar')->name('pedidos.procesar');
    Route::get('pedidos/cancelar/{tempPedido}', 'PedidoController@cancelar')->name('pedidos.cancelar');
    Route::get('pedidos/anular/{pedido}', 'PedidoController@anular')->name('pedidos.anular');
    Route::get('pedidos/fpdf/{pedido}', 'PedidoController@fpdf')->name('pedidos.fpdf');
    Route::get('pedidos/ingreso/{pedido}', 'PedidoController@ingreso')->name('pedidos.ingreso');
    Route::post('pedidos/ingreso/{pedido}', 'PedidoController@ingreso')->name('pedidos.ingreso');
    Route::get('pedidos/entrega/{pedido}', 'PedidoController@entrega')->name('pedidos.entrega');
    Route::post('pedidos/entrega/{pedido}', 'PedidoController@entrega')->name('pedidos.entrega');


    Route::resource('solicitudEstados', 'SolicitudEstadoController');
    Route::resource('solicitudes', 'SolicitudeController');
    Route::get('solicitudes/cancelar/{tempSolicitude}', 'SolicitudeController@cancelar')->name('solicitud.cancelar');
    Route::get('solicitudes/cancelar/solicitud/{solicitud}', 'SolicitudeController@cancelarSolicitud')->name('solicitud.cancelar.solicitud');
    Route::get('solicitudes/anular/{solicitud}', 'SolicitudeController@anular')->name('solicitud.anular');
    Route::get('mis/solicitudes', 'SolicitudeController@user')->name('mis.solicitudes');
    Route::get('lista/despachar/solicitudes', 'SolicitudeController@despacharList')->name('solicitudes.despachar');
    Route::get('despachar/solicitudes/{solicitud}', 'SolicitudeController@despachar')->name('solicitudes.despachar.store');

    Route::resource('notificacionTipos', 'NotificacionTipoController');
    Route::resource('repartidores', 'RepartidoreController');

    Route::get('user/despacha/user', 'UserController@asignar')->name('user.despacha.user');

    Route::get('pedidos', 'OrdenesController@index')->name('ordenes.index');
    Route::get('pedidos/datos', 'OrdenesController@datos')->name('ordenes.datos');
    Route::get('pedidos/cambio/estado', 'OrdenesController@cambioEstado')->name('ordenes.cambio.estado');
    Route::get('cocina', 'OrdenesController@cocina')->name('ordenes.cocina');
    Route::get('delivery', 'OrdenesController@delivery')->name('delivery.index');
    Route::get('delivery/caja', 'OrdenesController@deliveryCaja')->name('delivery.caja');
    Route::resource('ordenEstados', 'OrdenEstadoController');

    Route::resource('produccionTipos', 'ProduccionTipoController');
    Route::resource('produccionEstados', 'ProduccionEstadoController');
    Route::resource('producciones', 'ProduccioneController');
    Route::get('produccion/add', 'ProduccioneController@add')->name('produccion.add');
    Route::get('produccion/remove', 'ProduccioneController@remove')->name('produccion.remove');
    Route::get('produccion/solicitados/session', 'ProduccioneController@getSolicitadosSesion')->name('get.solicitados.session');
    Route::get('produccion/solicitados/{produccion}', 'ProduccioneController@getSolicitados')->name('get.solicitados');
    Route::get('produccion/materia/prima/sesion', 'ProduccioneController@getMateriaSesion')->name('produccion.get.materia.session');
    Route::get('produccion/materia/prima/{produccion}', 'ProduccioneController@getMateria')->name('produccion.get.materia');
    Route::get('produccion/cocina', 'ProduccioneController@cocinaList')->name('produccion.cocina.listado');
    Route::get('produccion/cocina/atender/{id}', 'ProduccioneController@cocinaAtender')->name('produccion.cocina.atender');
    Route::patch('produccion/cocina/{produccion}', 'ProduccioneController@storeCocina')->name('produccion.cocina.store');
    Route::post('produccion/cancelar/{produccion}', 'ProduccioneController@cancelar')->name('produccion.cancelar');
    Route::post('produccion/anular/{produccion}', 'ProduccioneController@anular')->name('produccion.anular');


    Route::resource('recetas', 'RecetaController');
    Route::get('receta/add', 'RecetaController@add')->name('recetas.add.det');
    Route::get('receta/remove', 'RecetaController@remove')->name('recetas.remove.det');
    Route::get('receta/session', 'RecetaController@getReceta')->name('get.receta.session');
    Route::get('receta/cancelar', 'RecetaController@cancelar')->name('receta.cancelar');

    Route::get('inventario/stock/tienda','InventarioController@index')->name('inventario.stock.tienda');
    Route::get('stock/produccion/mp','InventarioController@stockMp')->name('stock.produccion.mp');
    Route::get('stock/produccion/pf','InventarioController@stockPf')->name('stock.produccion.pf');
    Route::get('compra/ingreso/{id}','CompraController@ingreso')->name('compra.ingreso');

    Route::get('get/repartidores/ajax', 'OrdenesController@repartidores')->name('get.repartidores.ajax');
    Route::get('orden/delivery/attach', 'OrdenesController@attach')->name('orden.attach');

    Route::resource('tipoPagos', 'TipoPagoController');
    Route::get('get/denominaciones', 'DenominacioneController@getAjax')->name('get.denominaciones');
    Route::get('stock_critico', 'InventarioController@stockCriticoView')->name('stock.critico');
    Route::post('stock_critico', 'InventarioController@stockCriticoStore')->name('stock.critico.store');
    Route::get('get/total/dia', 'RptResumenController@getTotalAjax')->name('get.total.dia');
    Route::get('orden/print/cocina/{orden}', 'OrdenesController@imprimeCocina')->name('orden.print.cocina');

    Route::get('notificaciones/ver/{tipo}','NotificacionController@ver')->name('notificaciones.ver');

    Route::get('lugar/cambiar/{lugar}','TiendaController@cambiar')->name('lugar.cambiar');

    Route::get('banner','BannerClienteController@index')->name('admin.banner');

    Route::resource('ingredientes', 'IngredienteController');
});

Route::get('productos', 'OrderController@index')->name('productos');
Route::post('productos', 'OrderController@index')->name('productos');
Route::get('combos', 'OrderController@combos')->name('combos');
Route::view('producto', 'delivery.producto')->name('producto');

Route::post('carro', 'OrderController@vistaCarro')->name('modal.pagar');
Route::get('carro', 'OrderController@vistaCarro')->name('carro');

Route::group(['prefix' => 'cart'], function () {
    Route::get('/', 'CartController@index')->name('cart.index');
    Route::post('add-product', 'CartController@add')->name('add.cart');
    Route::get('remove-product/{id}', 'CartController@remove')->name('remove.cart');
    Route::post('pagar', 'OrderController@pagar')->name('carro.pagar');
    Route::post('autorizar', 'OrderController@autorizar')->name('carro.autorizar');
    Route::post('procesar/webpay', 'OrderController@procesarWebPay')->name('carro.procesar.webpay');
    Route::get('procesar/khipu', 'OrderController@procesarKhipu')->name('carro.procesar.khipu');

    Route::get('store/modify/item', 'OrderController@storeModifyItem')->name('carro.store.modify');


    Route::get('get/modificaciones', 'OrderController@getModificaciones')->name('carro.get.modificaciones');
});


Route::get('cuenta', 'AccountController@index');
Route::get('ejemplo', 'AccountController@ejemplo');

Route::get('locales', 'OrderController@locales')->name('locales');

Route::view('localescopia', 'delivery.localescopia');

Route::get('get/tienda/map', 'TiendaController@getPorIdMap')->name('get.tienda.map');

Route::get('pedir/local', 'OrderController@pedir')->name('pedir.local');
Route::post('pedir/local', 'OrderController@pedir')->name('pedir.ahora');

Route::get('cambiar/tipo/pedido/{tipo}', 'OrderController@cambiaTipoPedido')->name('orden.cambiar.tipo.pedido');

Route::post('orden/exito/{orden}', 'OrderController@exito')->name('orden.exito');
Route::get('orden/exito/{orden}', 'OrderController@exito')->name('orden.exito');
Route::get('seguir/comprando/{anterior}', 'OrderController@seguirComprando')->name('seguir.comprando');
Route::get ('local/detalles/{local}', 'OrderController@detalleLocal')->name('local.detalle');

Route::post('webhook','WebhookController@index');

app/Models/ProduccionEstado.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class ProduccionEstado
 * @package App\Models
 * @version August 10, 2018, 5:02 pm CST
 *
 * @property \Illuminate\Database\Eloquent\Collection compraDetalles
 * @property \Illuminate\Database\Eloquent\Collection compraPedidos
 * @property \Illuminate\Database\Eloquent\Collection compraVenta
 * @property \Illuminate\Database\Eloquent\Collection cpagos
 * @property \Illuminate\Database\Eloquent\Collection egresoSolicitud
 * @property \Illuminate\Database\Eloquent\Collection egresos
 * @property \Illuminate\Database\Eloquent\Collection equivalencias
 * @property \Illuminate\Database\Eloquent\Collection icategoriaItem
 * @property \Illuminate\Database\Eloquent\Collection ingresoSolicitud
 * @property \Illuminate\Database\Eloquent\Collection ingresos
 * @property \Illuminate\Database\Eloquent\Collection notificaciones
 * @property \Illuminate\Database\Eloquent\Collection optionUser
 * @property \Illuminate\Database\Eloquent\Collection ordenDetalles
 * @property \Illuminate\Database\Eloquent\Collection pedidoDetalles
 * @property \Illuminate\Database\Eloquent\Collection pedidoVentas
 * @property \Illuminate\Database\Eloquent\Collection pedidos
 * @property \Illuminate\Database\Eloquent\Collection Produccione
 * @property \Illuminate\Database\Eloquent\Collection productoConsumidos
 * @property \Illuminate\Database\Eloquent\Collection productoRealizados
 * @property \Illuminate\Database\Eloquent\Collection recetaDetalles
 * @property \Illuminate\Database\Eloquent\Collection recetas
 * @property \Illuminate\Database\Eloquent\Collection rolUser
 * @property \Illuminate\Database\Eloquent\Collection solicitudDetalles
 * @property \Illuminate\Database\Eloquent\Collection stocks
 * @property \Illuminate\Database\Eloquent\Collection tempCompraDetalles
 * @property \Illuminate\Database\Eloquent\Collection tempPedidoDetalles
 * @property \Illuminate\Database\Eloquent\Collection tempSolicitudDetalles
 * @property \Illuminate\Database\Eloquent\Collection tempVentaDetalles
 * @property \Illuminate\Database\Eloquent\Collection tiendaDespachaTienda
 * @property \Illuminate\Database\Eloquent\Collection userDespachaUser
 * @property \Illuminate\Database\Eloquent\Collection ventaDetalles
 * @property \Illuminate\Database\Eloquent\Collection vpagos
 * @property string nombre
 */
class ProduccionEstado extends Model
{
    use SoftDeletes;

    public $table = 'produccion_estados';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';

    const SOLICITADA = 1;
    const INCOMPLETA = 2;
    const COMPLETADA = 3;
    const CANCELADA = 4;
    const ANULADA = 5;


    protected $dates = ['deleted_at'];


    public $fillable = [
        'nombre'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'nombre' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'nombre' => 'required|max:100|unique:produccion_estados',
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     **/
    public function producciones()
    {
        return $this->hasMany(\App\Models\Produccione::class);
    }
}

app/Http/Controllers/ProduccionEstadoController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\ProduccionEstadoDataTable;
use App\Http\Requests;
use App\Http\Requests\CreateProduccionEstadoRequest;
use App\Http\Requests\UpdateProduccionEstadoRequest;
use App\Repositories\ProduccionEstadoRepository;
use Flash;
use App\Http\Controllers\AppBaseController;
use Response;

class ProduccionEstadoController extends AppBaseController
{
    /** @var  ProduccionEstadoRepository */
    private $produccionEstadoRepository;

    public function __construct(ProduccionEstadoRepository $produccionEstadoRepo)
    {
        $this->produccionEstadoRepository = $produccionEstadoRepo;
        $this->middleware('auth');
    }

    /**
     * Display a listing of the ProduccionEstado.
     *
     * @param ProduccionEstadoDataTable $produccionEstadoDataTable
     * @return Response
     */
    public function index(ProduccionEstadoDataTable $produccionEstadoDataTable)
    {
        return $produccionEstadoDataTable->render('produccion_estados.index');
    }

    /**
     * Show the form for creating a new ProduccionEstado.
     *
     * @return Response
     */
    public function create()
    {
        return view('produccion_estados.create');
    }

    /**
     * Store a newly created ProduccionEstado in storage.
     *
     * @param CreateProduccionEstadoRequest $request
     *
     * @return Response
     */
    public function store(CreateProduccionEstadoRequest $request)
    {
        $input = $request->all();

        $produccionEstado = $this->produccionEstadoRepository->create($input);

        Flash::success('Produccion Estado guardado exitosamente.');

        return redirect(route('produccionEstados.index'));
    }

    /**
     * Display the specified ProduccionEstado.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $produccionEstado = $this->produccionEstadoRepository->findWithoutFail($id);

        if (empty($produccionEstado)) {
            Flash::error('Produccion Estado no encontrado');

            return redirect(route('produccionEstados.index'));
        }

        return view('produccion_estados.show',compact('produccionEstado'));
    }

    /**
     * Show the form for editing the specified ProduccionEstado.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $produccionEstado = $this->produccionEstadoRepository->findWithoutFail($id);

        if (empty($produccionEstado)) {
            Flash::error('Produccion Estado no encontrado');

            return redirect(route('produccionEstados.index'));
        }

        return view('produccion_estados.edit',compact('produccionEstado'));
    }

    /**
     * Update the specified ProduccionEstado in storage.
     *
     * @param  int              $id
     * @param UpdateProduccionEstadoRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateProduccionEstadoRequest $request)
    {
        $produccionEstado = $this->produccionEstadoRepository->findWithoutFail($id);

        if (empty($produccionEstado)) {
            Flash::error('Produccion Estado no encontrado');

            return redirect(route('produccionEstados.index'));
        }

        $produccionEstado = $this->produccionEstadoRepository->update($request->all(), $id);

        Flash::success('Produccion Estado actualizado exitosamente.');

        return redirect(route('produccionEstados.index'));
    }

    /**
     * Remove the specified ProduccionEstado from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $produccionEstado = $this->produccionEstadoRepository->findWithoutFail($id);

        if (empty($produccionEstado)) {
            Flash::error('Produccion Estado no encontrado');

            return redirect(route('produccionEstados.index'));
        }

        $this->produccionEstadoRepository->delete($id);

        Flash::success('Produccion Estado eliminado exitosamente.');

        return redirect(route('produccionEstados.index'));
    }
}

resources/views/produccion_estados/create.blade.php
@extends('layouts.app')

@section('htmlheader_title')
	Crear Produccion Estado
@endsection

@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row">
                <div class="col">
                    <h1 class="m-0 text-dark">
                        Crear Produccion Estado
                    </h1>
                </div><!-- /.col -->
                <div class="col ">
                    <a class="btn btn-outline-info float-right"
                       href="{{route('produccionEstados.index')}}">
                        <i class="fa fa-list" aria-hidden="true"></i>&nbsp;<span class="d-none d-sm-inline">Listado</span>
                    </a>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
        <div class="container-fluid">
            @include('flash::message')
            @include('adminlte-templates::common.errors')

            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-body">
                            {!! Form::open(['route' => 'produccionEstados.store']) !!}
                                <div class="form-row">

                                    @include('produccion_estados.fields')
                                    <!-- Submit Field -->
                                    <div class="form-group col-sm-12">
                                        <button type="submit" onClick="this.form.submit(); this.disabled=true;" class="btn btn-outline-success">Guardar</button>
                                        <a href="{!! route('produccionEstados.index') !!}" class="btn btn-outline-default">Cancelar</a>
                                    </div>
                                </div>
                            {!! Form::close() !!}
                        </div>
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col-md-6 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </div>
    <!-- /.content -->


@endsection

resources/views/produccion_estados/datatables_actions.blade.php
<a href="{{ route('produccionEstados.show', $id) }}" class='btn btn-default btn-xs' data-toggle="tooltip" title="Ver">
    <i class="fa fa-eye"></i>
</a>

<a href="{{ route('produccionEstados.edit', $id) }}" class='btn btn-info btn-xs' data-toggle="tooltip" title="Editar">
    <i class="fa fa-edit"></i>
</a>

<span data-toggle="tooltip" title="Eliminar">
    <a href="#modal-delete-{{$id}}" data-toggle="modal" data-keyboard="true" class='btn btn-danger btn-xs'>
        <i class="fa fa-trash-alt"></i>
    </a>
</span>

<!-- Modal-->
<div class="modal fade" id="modal-delete-{{$id}}" tabindex="-1" role="dialog" aria-labelledby="modalLogoutLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content ">
            <div class="modal-header">
                <h5 class="modal-title" >
                    <i class="fa fa-warning text-warning fa-2x" aria-hidden="true"></i> &nbsp;¿Eliminar?
                </h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">Seleccione "SI" a continuación si está seguro de eliminar el registro.</div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
                {!! Form::open(['route' => ['produccionEstados.destroy', $id], 'method' => 'delete']) !!}
                    <button type="submit" class="btn btn-danger">SI</button>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
</div>
<!-- /.modal -->

resources/views/produccion_estados/edit.blade.php
@extends('layouts.app')

@section('htmlheader_title')
	Editar Produccion Estado
@endsection

@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row">
                <div class="col">
                    <h1 class="m-0 text-dark">
                        Editar Produccion Estado
                    </h1>
                </div><!-- /.col -->
                <div class="col">
                    <a class="btn btn-outline-info float-right"
                       href="{{route('produccionEstados.index')}}">
                        <i class="fa fa-list" aria-hidden="true"></i>&nbsp;<span class="d-none d-sm-inline">Listado</span>
                    </a>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
        <div class="container-fluid">
            @include('flash::message')
            @include('adminlte-templates::common.errors')

            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-body">

                           {!! Form::model($produccionEstado, ['route' => ['produccionEstados.update', $produccionEstado->id], 'method' => 'patch']) !!}
                                <div class="form-row">

                                    @include('produccion_estados.fields')
                                    <!-- Submit Field -->
                                    <div class="form-group col-sm-12">
                                        <button type="submit" onClick="this.form.submit(); this.disabled=true;" class="btn btn-outline-success">Guardar</button>
                                        <a href="{!! route('produccionEstados.index') !!}" class="btn btn-outline-default">Cancelar</a>
                                    </div>
                                </div>

                           {!! Form::close() !!}

                        </div>
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col-md-6 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </div>
    <!-- /.content -->


@endsection

resources/views/produccion_estados/fields.blade.php
<!-- Nombre Field -->
<div class="form-group col-sm-6">
    {!! Form::label('nombre', 'Nombre:') !!}
    {!! Form::text('nombre', null, ['class' => 'form-control']) !!}
</div>

resources/views/produccion_estados/index.blade.php
@extends('layouts.app')

@section('htmlheader_title')
	Produccion Estados
@endsection

@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row">
                <div class="col">
                    <h1 class="m-0 text-dark">Produccion Estados</h1>
                </div><!-- /.col -->
                <div class="col">
                    <ol class="breadcrumb float-right">
                        <li class="breadcrumb-item">
                            <a class="btn btn-outline-success"
                                href="{!! route('produccionEstados.create') !!}">
                                <i class="fa fa-plus"></i>
                                <span class="d-none d-sm-inline">Agregar Nuevo</span>
                            </a>
                        </li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
        <div class="container-fluid">
            @include('flash::message')

            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-body">
                           @include('produccion_estados.table')
                        </div>
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col-md-6 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </div>
    <!-- /.content -->
@endsection

resources/views/produccion_estados/show.blade.php
@extends('layouts.app')

@section('htmlheader_title')
	Produccion Estado
@endsection

@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <h1 class="m-0 text-dark">Produccion Estado</h1>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->


    <!-- Main content -->
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-body">
                           @include('produccion_estados.show_fields')
                        </div>
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col-md-6 -->
            </div>
            <!-- /.row -->

            <div class="row">
                <div class="form-group col-sm-12">
                <a href="{!! route('produccionEstados.index') !!}" class="btn btn-default">Regresar</a>
                </div>
            </div>
        </div>
        <!-- /.container-fluid -->
    </div>
    <!-- /.content -->
@endsection

resources/views/produccion_estados/show_fields.blade.php
<!-- Id Field -->
{!! Form::label('id', 'Id:') !!}
{!! $produccionEstado->id !!}<br>


<!-- Nombre Field -->
{!! Form::label('nombre', 'Nombre:') !!}
{!! $produccionEstado->nombre !!}<br>


<!-- Created At Field -->
{!! Form::label('created_at', 'Creado el:') !!}
{!! $produccionEstado->created_at->format('Y/m/d H:i:s')!!}<br>


<!-- Updated At Field -->
{!! Form::label('updated_at', 'Actualizado el:') !!}
{!! $produccionEstado->updated_at->format('Y/m/d H:i:s')!!}<br>


<!-- Deleted At Field -->
{!! Form::label('deleted_at', 'Borrado el:') !!}
{!! $produccionEstado->deleted_at !!}<br>

resources/views/produccion_estados/table.blade.php
@section('css')
    @include('layouts.datatables_css')
@endsection

<div class="table-responsive">
    {!! $dataTable->table(['width' => '100%']) !!}
</div>

@section('scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
    <script>
        $(function () {
            var dt = window.LaravelDataTables["dataTableBuilder"];

            //Cuando dibuja la tabla
            dt.on( 'draw.dt', function () {
                $(this).addClass('table-sm table-striped table-bordered table-hover');
            });

        })
    </script>
@endsection