routes/web.php
    Route::resource('rols', 'RolController');
    Route::get('rol/detach/{user}/{rol}','RolController@detach')->name('rol.detach');
    Route::resource('configurations', 'ConfigurationController');
    Route::resource('admin/empleados', 'EmpleadoController');
    Route::resource('horarios', 'HorarioController');
    Route::resource('correlativos', 'CorrelativoController');
    Route::resource('licencias', 'LicenciaController');
    Route::resource('denominaciones', 'DenominacioneController');
    Route::resource('tipoMarcajes', 'TipoMarcajeController');
    Route::resource('marcajes', 'MarcajeController');

    Route::resource('combos', 'ComboController');
    Route::get('combo/add', 'ComboController@add')->name('combos.add.det');
    Route::get('combo/remove', 'ComboController@remove')->name('combos.remove.det');
    Route::get('combo/session', 'ComboController@getCombo')->name('get.combo.session');
    Route::get('combo/cancelar', 'ComboController@cancelar')->name('combos.cancelar');

    /**
     * Rutas para usuario
     */
    Route::get('user/profile/{user}', 'UserController@editProfile')->name('user.edit.profile');;
    Route::patch('user/profile/{user}', 'UserController@updateProfile')->name('user.update.profile');
    Route::resource('users', 'UserController');
    Route::get('/admin/user/{user}/menu', 'UserController@menu')->name('user.menu');;
    Route::patch('/admin/user/menu/{user}', 'UserController@menuStore')->name('users.menuStore');

    /**
     * Rutas para administrar opciones
     */
    Route::get('/admin/option/create/{padre}', 'OptionMenuController@create')->name('admin.option.create');
    Route::get('option/orden', 'OptionMenuController@updateOrden')->name('option.order.store');
    Route::resource('/admin/option',"OptionMenuController");

    /**
     * Rutas para inventario
     */
    Route::resource('inventario/icategorias', 'IcategoriaController');
    Route::resource('inventario/unimeds', 'UnimedController');
    Route::resource('inventario/iestados', 'IestadoController');
    Route::resource('inventario/items', 'ItemController');
    Route::get('inventario/items/clonar/{item}', 'ItemController@clonar')->name('items.clonar');
    Route::get('inventario/items/precio/compra/cero', 'ItemController@precioCostoCeroView')->name('items.precio.compra.cero');
    Route::post('inventario/items/precio/compra/cero', 'ItemController@precioCostoCeroStore')->name('items.store.precio.compra');
    Route::get('inventario/items/add/ingrediente', 'ItemController@addIngrediente')->name('items.add.ingrediente');
    Route::get('inventario/items/get/ingredientes', 'ItemController@getIngredientes')->name('item.get.ingredientes');
    Route::get('inventario/items/remove/ingrediente', 'ItemController@removeIngrediente')->name('item.remover.ingredientes');
    Route::get('inventario/items/get/agregados', 'ItemController@getAgregados')->name('item.get.agregados');
    Route::get('inventario/items/attach/agregados', 'ItemController@attachAgregados')->name('item.attach.agregados');
    Route::get('inventario/items/detach/agregados', 'ItemController@detachAgregados')->name('item.detach.agregados');

    Route::resource('inventario/marcas', 'MarcaController');
    Route::resource('inventario/cajas', 'CajaController');
    Route::resource('inventario/tiendas', 'TiendaController');
    Route::resource('inventario/descuentos', 'DescuentoController');
    Route::resource('inventario/magnitudes', 'MagnitudeController');
    Route::resource('traslados', 'TrasladoController');

    /**
     * Rutas para compras
     */
    Route::resource('compras/proveedores', 'ProveedorController');
    Route::resource('compras/cestados', 'CestadoController');
    Route::resource('compras/tcomprobantes', 'TcomprobanteController');
    Route::resource('compras/compras', 'CompraController');
    Route::get('compras/cancelar/{tempCompra}', 'CompraController@cancelar')->name('compras.cancelar');
    Route::get('compras/cancelar/solicitud/{compra}', 'CompraController@cancelarSolicictud')->name('compras.cancelar.solicitud');
    Route::get('compras/anular/{compra}', 'CompraController@anular')->name('compras.anular');
    Route::get('compras/pagar', 'CompraController@pagar')->name('compras.pagar');
    Route::get('compras/abonar/{venta}', 'CompraController@abonarView')->name('compras.abonar');
    Route::get('compras/factura/pdf/{compra}', 'CompraController@pdf')->name('compra.pdf');

    /**
     * Rutas para ventas
     */
    Route::resource('ventas/vestados', 'VestadoController');
    Route::resource('ventas/clientes', 'ClienteController');
    Route::resource('ventas/ventas', 'VentaController');
    Route::get('ventas/cancelar/{tempVenta}', 'VentaController@cancelar')->name('ventas.cancelar');
    Route::get('ventas/anular/{venta}', 'VentaController@anular')->name('ventas.anular');
    Route::get('ventas/factura/pdf/{venta}', 'VentaController@pdfFactura')->name('ventas.pdf_factura');
    Route::get('ventas/factura/pdf2/{venta}', 'VentaController@factura')->name('ventas.pdf_factura2');
    Route::get('ventas/factura/{venta}', 'VentaController@facturaView')->name('ventas.factura');
    Route::get('ventas/comprobante/{venta}', 'VentaController@comprobanteView')->name('ventas.comprobante.view');
    Route::resource('ventas/tpagos', 'TpagoController');
    Route::get('ventas/cobrar', 'VentaController@cobrar')->name('ventas.por_cobrar');
    Route::get('ventas/abonar/{venta}', 'VentaController@abonarView')->name('ventas.abonar');
    Route::get('ventas/ajax/anular', 'OrdenesController@anular')->name('ventas.anular.ajax');
    Route::get('ventas/ticket/pdf/{venta}', 'VentaController@ticket')->name('ventas.ticket.pdf');
    Route::get('ventas/ticket/{venta}', 'VentaController@viewTicket')->name('ventas.ticket.view');
    Route::post('venta/store/{tempVenta}', 'VentaController@store')->name('venta.store');
    Route::get('venta/verifica/caja', 'VentaController@verificaCajaAjax')->name('venta.verifica.caja');
    Route::get('venta/get/modificaciones', 'VentaController@getModificaciones')->name('venta.get.modificaciones');
    Route::get('venta/store/modify/det', 'VentaController@storeModifyDet')->name('venta.store.modify');
    Route::get('venta/temp/detalles/{venta}', 'VentaController@getDetalles')->name('venta.temp.detalles');

    /**
     * Rutas para graficas
     */
    Route::get('graficas/ventas/dia', 'DashBoardController@graficaVentasDia')->name('graficas.ventas.dia');
    Route::get('graficas/ventas/mes', 'DashBoardController@graficaVentasMes')->name('graficas.ventas.mes');
    Route::get('graficas/ventas/anio', 'DashBoardController@graficaVentasAnio')->name('graficas.ventas.anio');

    /**
     * Rutas para reportes
     */
    Route::get('rpt/ventas/cat', 'RptVentasController@index')->name('rpt.ventas.cats');
    Route::get('rpt/ventas/cat/res', 'RptVentasController@porCatRes')->name('rpt.ventas.cats.res')->middleware(\App\Http\Middleware\SuperAdmin::class);
    Route::get('rpt/resumen', 'RptResumenController@index')->name('rpt.resumen');
    Route::get('rpt/kardex', 'RptGenController@kardex')->name('rpt.kardex');
    Route::get('rpt/gastos', 'GastoController@rpt')->name('rpt.gastos');
    Route::get('rpt/stock','StockController@rpt')->name('rpt.stock');
    Route::get('rpt/compras/','CompraController@rptComprasDiarias')->name('rpt.compras');

    /**
     * Rutas para contabilidad
     */
    Route::resource('gastos', 'GastoController');
    Route::resource('cretiros', 'CretiroController');
    Route::get('cajas/retiro', 'CretiroController@create')->name('caja.retiro');
    Route::resource('cuadres', 'CuadreController');

    /**
     * Rutas para pedidos
     */
    Route::resource('pedidos/pestados', 'PestadoController');
    Route::resource('pedidos/pedidos', 'PedidoController');
    Route::post('pedidos/procesar/{tempPedido}', 'PedidoController@procesar')->name('pedidos.procesar');
    Route::get('pedidos/cancelar/{tempPedido}', 'PedidoController@cancelar')->name('pedidos.cancelar');
    Route::get('pedidos/anular/{pedido}', 'PedidoController@anular')->name('pedidos.anular');
    Route::get('pedidos/fpdf/{pedido}', 'PedidoController@fpdf')->name('pedidos.fpdf');
    Route::get('pedidos/ingreso/{pedido}', 'PedidoController@ingreso')->name('pedidos.ingreso');
    Route::post('pedidos/ingreso/{pedido}', 'PedidoController@ingreso')->name('pedidos.ingreso');
    Route::get('pedidos/entrega/{pedido}', 'PedidoController@entrega')->name('pedidos.entrega');
    Route::post('pedidos/entrega/{pedido}', 'PedidoController@entrega')->name('pedidos.entrega');


    Route::resource('solicitudEstados', 'SolicitudEstadoController');
    Route::resource('solicitudes', 'SolicitudeController');
    Route::get('solicitudes/cancelar/{tempSolicitude}', 'SolicitudeController@cancelar')->name('solicitud.cancelar');
    Route::get('solicitudes/cancelar/solicitud/{solicitud}', 'SolicitudeController@cancelarSolicitud')->name('solicitud.cancelar.solicitud');
    Route::get('solicitudes/anular/{solicitud}', 'SolicitudeController@anular')->name('solicitud.anular');
    Route::get('mis/solicitudes', 'SolicitudeController@user')->name('mis.solicitudes');
    Route::get('lista/despachar/solicitudes', 'SolicitudeController@despacharList')->name('solicitudes.despachar');
    Route::get('despachar/solicitudes/{solicitud}', 'SolicitudeController@despachar')->name('solicitudes.despachar.store');

    Route::resource('notificacionTipos', 'NotificacionTipoController');
    Route::resource('repartidores', 'RepartidoreController');

    Route::get('user/despacha/user', 'UserController@asignar')->name('user.despacha.user');

    Route::get('pedidos', 'OrdenesController@index')->name('ordenes.index');
    Route::get('pedidos/datos', 'OrdenesController@datos')->name('ordenes.datos');
    Route::get('pedidos/cambio/estado', 'OrdenesController@cambioEstado')->name('ordenes.cambio.estado');
    Route::get('cocina', 'OrdenesController@cocina')->name('ordenes.cocina');

app/Models/Descuento.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class Descuento
 *
 * @package App\Models
 * @version June 25, 2017, 6:20 pm CST
 * @property int $id
 * @property int $item_id
 * @property int $porcentaje
 * @property string|null $fecha_inicio
 * @property string|null $fecha_expira
 * @property \Carbon\Carbon|null $created_at
 * @property \Carbon\Carbon|null $updated_at
 * @property \Carbon\Carbon|null $deleted_at
 * @property-read \App\Models\Item $item
 * @method static bool|null forceDelete()
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Descuento onlyTrashed()
 * @method static bool|null restore()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Descuento whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Descuento whereDeletedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Descuento whereFechaExpira($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Descuento whereFechaInicio($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Descuento whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Descuento whereItemId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Descuento wherePorcentaje($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Descuento whereUpdatedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Descuento withTrashed()
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Descuento withoutTrashed()
 * @mixin \Eloquent
 */
class Descuento extends Model
{
    use SoftDeletes;

    public $table = 'descuentos';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];


    public $fillable = [
        'item_id',
        'porcentaje',
        'fecha_inicio',
        'fecha_expira'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'item_id' => 'integer',
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'item_id' => 'required',
        'porcentaje' => 'required|numeric|digits_between:1,2|between:0,100',
        'fecha_inicio' => 'required|date',
        'fecha_expira' => 'required|date'

    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function item()
    {
        return $this->belongsTo(\App\Models\Item::class);
    }

    public function getFechaInicioAttribute($d)
    {
        return fecha($d);
    }

    public function getFechaExpiraAttribute($d)
    {
        return fecha($d);
    }
}

app/Http/Controllers/DescuentoController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\DescuentoDataTable;
use App\Http\Requests;
use App\Http\Requests\CreateDescuentoRequest;
use App\Http\Requests\UpdateDescuentoRequest;
use App\Repositories\DescuentoRepository;
use Flash;
use App\Http\Controllers\AppBaseController;
use Response;

class DescuentoController extends AppBaseController
{
    /** @var  DescuentoRepository */
    private $descuentoRepository;

    public function __construct(DescuentoRepository $descuentoRepo)
    {
        $this->middleware("auth");
        $this->descuentoRepository = $descuentoRepo;
    }

    /**
     * Display a listing of the Descuento.
     *
     * @param DescuentoDataTable $descuentoDataTable
     * @return Response
     */
    public function index(DescuentoDataTable $descuentoDataTable)
    {
        return $descuentoDataTable->render('descuentos.index');
    }

    /**
     * Show the form for creating a new Descuento.
     *
     * @return Response
     */
    public function create()
    {
        return view('descuentos.create');
    }

    /**
     * Store a newly created Descuento in storage.
     *
     * @param CreateDescuentoRequest $request
     *
     * @return Response
     */
    public function store(CreateDescuentoRequest $request)
    {
        $input = $request->all();

        $descuento = $this->descuentoRepository->create($input);

        Flash::success('Descuento saved successfully.');

        return redirect(route('descuentos.index'));
    }

    /**
     * Display the specified Descuento.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $descuento = $this->descuentoRepository->findWithoutFail($id);

        if (empty($descuento)) {
            Flash::error('Descuento not found');

            return redirect(route('descuentos.index'));
        }

        return view('descuentos.show')->with('descuento', $descuento);
    }

    /**
     * Show the form for editing the specified Descuento.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $descuento = $this->descuentoRepository->findWithoutFail($id);

        if (empty($descuento)) {
            Flash::error('Descuento not found');

            return redirect(route('descuentos.index'));
        }

        return view('descuentos.edit')->with('descuento', $descuento);
    }

    /**
     * Update the specified Descuento in storage.
     *
     * @param  int              $id
     * @param UpdateDescuentoRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateDescuentoRequest $request)
    {
        $descuento = $this->descuentoRepository->findWithoutFail($id);

        if (empty($descuento)) {
            Flash::error('Descuento not found');

            return redirect(route('descuentos.index'));
        }

        $descuento = $this->descuentoRepository->update($request->all(), $id);

        Flash::success('Descuento updated successfully.');

        return redirect(route('descuentos.index'));
    }

    /**
     * Remove the specified Descuento from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $descuento = $this->descuentoRepository->findWithoutFail($id);

        if (empty($descuento)) {
            Flash::error('Descuento not found');

            return redirect(route('descuentos.index'));
        }

        $this->descuentoRepository->delete($id);

        Flash::success('Descuento deleted successfully.');

        return redirect(route('descuentos.index'));
    }
}

resources/views/descuentos/create.blade.php
@extends('adminlte::layouts.app')

@include('layouts.plugins.select2')
@include('layouts.plugins.bootstrap_datetimepicker')

@section('content')
    <section class="content-header">
        <h1>
            Descuento
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'descuentos.store']) !!}

                        @include('descuentos.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/descuentos/datatables_actions.blade.php
<a href="{{ route('descuentos.show', $id) }}" class='btn btn-default btn-xs' data-toggle="tooltip" title="Ver">
    <i class="glyphicon glyphicon-eye-open"></i>
</a>

<a href="{{ route('descuentos.edit', $id) }}" class='btn btn-info btn-xs' data-toggle="tooltip" title="Editar">
    <i class="glyphicon glyphicon-edit"></i>
</a>

<span data-toggle="tooltip" title="Eliminar">
    <a href="#modal-delete-{{$id}}" data-toggle="modal" class='btn btn-danger btn-xs'>
        <i class="glyphicon glyphicon-remove"></i>
    </a>
</span>

<div class="modal fade modal-warning" id="modal-delete-{{$id}}">
    <div class="modal-dialog">
        <div class="modal-content">
            {!! Form::open(['route' => ['descuentos.destroy', $id], 'method' => 'delete']) !!}
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Eliminar!</h4>
            </div>
            <div class="modal-body">
                Seguro que desea eliminar el Descuento?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
                <button type="submit" class="btn btn-danger">SI</button>
            </div>
            {!! Form::close() !!}
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

resources/views/descuentos/edit.blade.php
@extends('adminlte::layouts.app')

@include('layouts.plugins.select2')
@include('layouts.plugins.bootstrap_datetimepicker')

@section('content')
    <section class="content-header">
        <h1>
            Descuento
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($descuento, ['route' => ['descuentos.update', $descuento->id], 'method' => 'patch']) !!}

                        @include('descuentos.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/descuentos/fields.blade.php
@push('css')
<style>
    .select2-container--default .select2-selection--multiple .select2-selection__choice{
        color: #0A0A0A;
    }
</style>
@endpush
<!-- Item Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('item_id', 'Artículo:') !!}
    {!! Form::select('item_id', [] ,null,['class' => 'form-control', 'id'=>'items','multiple'=>"multiple",'style' => "width: 100%"]) !!}
</div>

<!-- Porcentaje Field -->
<div class="form-group col-sm-6">
    {!! Form::label('porcentaje', 'Porcentaje: ') !!}
    {!! Form::text('porcentaje', null, ['class' => 'form-control']) !!}
</div>

<!-- Fecha Inicio Field -->
<div class="form-group col-sm-6">
    {!! Form::label('fecha_inicio', 'Fecha Inicio:') !!}
    {!! Form::text('fecha_inicio', null, ['class' => 'form-control date']) !!}
</div>

<!-- Fecha Expira Field -->
<div class="form-group col-sm-6">
    {!! Form::label('fecha_expira', 'Fecha Expira:') !!}
    {!! Form::text('fecha_expira', null, ['class' => 'form-control date']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    <button type="submit" onClick="this.form.submit(); this.disabled=true;" class="btn btn-success">Guardar</button>
    <a href="{!! route('descuentos.index') !!}" class="btn btn-default">Cancel</a>
</div>
@push('scripts')
<script>
    $(function () {
        function formatStateItems (state) {

            var imagen= state.imagen==undefined ? 'img/avatar_none.png' : state.imagen;

            var color_stock_less = (state.stock<=0) ? 'color_stock_less' : '';

            var $state = $(
                "@component('components.format_slc2_item')"+
                "@slot('imagen')"+imagen+ "@endslot"+
                "@slot('nombre')"+state.nombre+ "@endslot"+
                "@slot('marca')"+state.nombre_marca+ "@endslot"+
                "@slot('descripcion')"+ state.descripcion+"@endslot"+
                "@slot('precio')"+state.precio_venta+"@endslot"+
                "@slot('ubicacion')"+state.ubicacion+"@endslot"+
                "@slot('stock')"+state.stock+"@endslot"+
                "@slot('color_stock_less')"+color_stock_less+"@endslot"+
                "@endcomponent"
            );

            return $state;
        };

        var slc2item=$("#items").select2({
            language : 'es',
            maximumSelectionLength: 1,
            placeholder: "Ingrese código,nombre o descripción para la búsqueda",
            delay: 250,
            ajax: {
                url: "{{ route('api.items.index') }}",
                dataType: 'json',
                data: function (params) {
                    return {
                        search: params.term
                    };
                },
                processResults: function (data, params) {
                    //recorre todos los item q
                    var data = $.map(data.data, function (item) {

                        //recorre los atributos del item
                        $.each(item,function (index,valor) {
                            //Si no existe valor se asigan un '-' al attributo
                            item[index] = !valor ? '-' : valor;
                        });

                        return item;
                    });

                    return {
                        results: data,
                    };
                },
                cache: true
            },
            minimumInputLength: 1,
            allowClear: true,
            templateResult: formatStateItems,
            templateSelection: function(data,contenedor) {

                //si se esta editando el descuento
                @if(isset($descuento->id))
                    return '{{$descuento->item->nombre}}';
                @else
                    return data.nombre;
                @endif

            }
        })

        var hoy=new Date();

        var manana=new Date(hoy.getTime() + 24*60*60*1000);

        $("#fecha_inicio").datetimepicker({
            format: 'DD/MM/YYYY',
            minDate: hoy
        })

        $("#fecha_expira").datetimepicker({
            format: 'DD/MM/YYYY',
            minDate: manana
        })

        //si se esta editando el descuento
        @if(isset($descuento->id))

            var option = new Option('{{$descuento->item->nombre}}', '{{$descuento->item->id}}');
            option.selected = true;

            slc2item.append(option).trigger("change");
        @endif

    })
</script>
@endpush

resources/views/descuentos/index.blade.php
@extends('adminlte::layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Descuentos</h1>
        <h1 class="pull-right">
           <a class="btn btn-success pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('descuentos.create') !!}">Agregar Nuevo</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('descuentos.table')
            </div>
        </div>
    </div>
@endsection

resources/views/descuentos/show.blade.php
@extends('adminlte::layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Descuento
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('descuentos.show_fields')
                    <a href="{!! route('descuentos.index') !!}" class="btn btn-default">Regresar</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/descuentos/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $descuento->id !!}</p>
</div>

<!-- Item Id Field -->
<div class="form-group">
    {!! Form::label('item_id', 'Item Id:') !!}
    <p>{!! $descuento->item_id !!}</p>
</div>

<!-- Porcentaje Field -->
<div class="form-group">
    {!! Form::label('porcentaje', 'Porcentaje:') !!}
    <p>{!! $descuento->porcentaje !!}</p>
</div>

<!-- Fecha Inicio Field -->
<div class="form-group">
    {!! Form::label('fecha_inicio', 'Fecha Inicio:') !!}
    <p>{!! $descuento->fecha_inicio !!}</p>
</div>

<!-- Fecha Expira Field -->
<div class="form-group">
    {!! Form::label('fecha_expira', 'Fecha Expira:') !!}
    <p>{!! $descuento->fecha_expira !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Creado el:') !!}
    <p>{!! $descuento->created_at->format('Y/m/d H:i:s')!!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Actualizado el:') !!}
    <p>{!! $descuento->updated_at->format('Y/m/d H:i:s')!!}</p>
</div>

<!-- Deleted At Field -->
<div class="form-group">
    {!! Form::label('deleted_at', 'Borrado el:') !!}
    <p>{!! $descuento->deleted_at !!}</p>
</div>

resources/views/descuentos/table.blade.php
@section('css')
    @include('layouts.datatables_css')
@endsection

{!! $dataTable->table(['width' => '100%']) !!}

@section('scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endsection